[package]
name = "xdp_router"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya", package = "aya-ebpf" }
network-types = "0.8"

[lib]
crate-type = ["cdylib"]